"""Init

Revision ID: c91c9bd79b59
Revises: 
Create Date: 2020-11-01 21:32:15.473726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c91c9bd79b59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('wotd_registered', sa.Boolean(), nullable=False),
    sa.Column('wotd', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('drawing_name', sa.String(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('timezone', sa.Integer(), nullable=False),
    sa.Column('auto_drawing', sa.Time(), nullable=True),
    sa.Column('fast_drawing', sa.Boolean(), nullable=True),
    sa.Column('admin_drawing', sa.Boolean(), nullable=True),
    sa.Column('opt_in_drawing', sa.Boolean(), nullable=True),
    sa.Column('show_userlist', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('group', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('can_change_name', sa.Boolean(), nullable=True),
    sa.Column('win_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('win_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_user_id', sa.Integer(), nullable=False),
    sa.Column('win_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_user_id'], ['chat_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('win_history')
    op.drop_table('chat_users')
    op.drop_table('chat_texts')
    op.drop_table('chats')
    op.drop_table('users')
    # ### end Alembic commands ###
